:concurrency: 5
:queues:
  - default

production:
  :concurrency: 5
  :queues:
    - default
  :redis:
    :url: <%= ENV.fetch("REDISCLOUD_URL") { ENV.fetch("REDIS_URL", "redis://localhost:6379/1") } %>
